// Code generated by protoc-gen-go. DO NOT EDIT.
// source: procpb/proc_1.proto

package procpb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Greeting struct {
	Network              string   `protobuf:"bytes,1,opt,name=network,proto3" json:"network,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Greeting) Reset()         { *m = Greeting{} }
func (m *Greeting) String() string { return proto.CompactTextString(m) }
func (*Greeting) ProtoMessage()    {}
func (*Greeting) Descriptor() ([]byte, []int) {
	return fileDescriptor_29c6dee84e051e2d, []int{0}
}

func (m *Greeting) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Greeting.Unmarshal(m, b)
}
func (m *Greeting) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Greeting.Marshal(b, m, deterministic)
}
func (m *Greeting) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Greeting.Merge(m, src)
}
func (m *Greeting) XXX_Size() int {
	return xxx_messageInfo_Greeting.Size(m)
}
func (m *Greeting) XXX_DiscardUnknown() {
	xxx_messageInfo_Greeting.DiscardUnknown(m)
}

var xxx_messageInfo_Greeting proto.InternalMessageInfo

func (m *Greeting) GetNetwork() string {
	if m != nil {
		return m.Network
	}
	return ""
}

func (m *Greeting) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type GreetRequest struct {
	Greeting             *Greeting `protobuf:"bytes,1,opt,name=greeting,proto3" json:"greeting,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *GreetRequest) Reset()         { *m = GreetRequest{} }
func (m *GreetRequest) String() string { return proto.CompactTextString(m) }
func (*GreetRequest) ProtoMessage()    {}
func (*GreetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_29c6dee84e051e2d, []int{1}
}

func (m *GreetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GreetRequest.Unmarshal(m, b)
}
func (m *GreetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GreetRequest.Marshal(b, m, deterministic)
}
func (m *GreetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GreetRequest.Merge(m, src)
}
func (m *GreetRequest) XXX_Size() int {
	return xxx_messageInfo_GreetRequest.Size(m)
}
func (m *GreetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GreetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GreetRequest proto.InternalMessageInfo

func (m *GreetRequest) GetGreeting() *Greeting {
	if m != nil {
		return m.Greeting
	}
	return nil
}

type GreetResponse struct {
	Result               string   `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GreetResponse) Reset()         { *m = GreetResponse{} }
func (m *GreetResponse) String() string { return proto.CompactTextString(m) }
func (*GreetResponse) ProtoMessage()    {}
func (*GreetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_29c6dee84e051e2d, []int{2}
}

func (m *GreetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GreetResponse.Unmarshal(m, b)
}
func (m *GreetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GreetResponse.Marshal(b, m, deterministic)
}
func (m *GreetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GreetResponse.Merge(m, src)
}
func (m *GreetResponse) XXX_Size() int {
	return xxx_messageInfo_GreetResponse.Size(m)
}
func (m *GreetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GreetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GreetResponse proto.InternalMessageInfo

func (m *GreetResponse) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

func init() {
	proto.RegisterType((*Greeting)(nil), "first_proc.Greeting")
	proto.RegisterType((*GreetRequest)(nil), "first_proc.GreetRequest")
	proto.RegisterType((*GreetResponse)(nil), "first_proc.GreetResponse")
}

func init() {
	proto.RegisterFile("procpb/proc_1.proto", fileDescriptor_29c6dee84e051e2d)
}

var fileDescriptor_29c6dee84e051e2d = []byte{
	// 204 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0x12, 0x2e, 0x28, 0xca, 0x4f,
	0x2e, 0x48, 0xd2, 0x07, 0x51, 0xf1, 0x86, 0x7a, 0x40, 0xaa, 0x24, 0x5f, 0x88, 0x2b, 0x2d, 0xb3,
	0xa8, 0xb8, 0x24, 0x1e, 0x24, 0xa6, 0x64, 0xc1, 0xc5, 0xe1, 0x5e, 0x94, 0x9a, 0x5a, 0x92, 0x99,
	0x97, 0x2e, 0x24, 0xc1, 0xc5, 0x9e, 0x97, 0x5a, 0x52, 0x9e, 0x5f, 0x94, 0x2d, 0xc1, 0xa8, 0xc0,
	0xa8, 0xc1, 0x19, 0x04, 0xe3, 0x0a, 0x09, 0x71, 0xb1, 0xe4, 0x25, 0xe6, 0xa6, 0x4a, 0x30, 0x81,
	0x85, 0xc1, 0x6c, 0x25, 0x07, 0x2e, 0x1e, 0xb0, 0xce, 0xa0, 0xd4, 0xc2, 0xd2, 0xd4, 0xe2, 0x12,
	0x21, 0x03, 0x2e, 0x8e, 0x74, 0xa8, 0x49, 0x60, 0xed, 0xdc, 0x46, 0x22, 0x7a, 0x08, 0x8b, 0xf4,
	0x60, 0xb6, 0x04, 0xc1, 0x55, 0x29, 0xa9, 0x73, 0xf1, 0x42, 0x4d, 0x28, 0x2e, 0xc8, 0xcf, 0x2b,
	0x4e, 0x15, 0x12, 0xe3, 0x62, 0x2b, 0x4a, 0x2d, 0x2e, 0xcd, 0x29, 0x81, 0xda, 0x0f, 0xe5, 0x19,
	0xf9, 0x72, 0x71, 0x07, 0x00, 0xcd, 0x08, 0x4e, 0x2d, 0x2a, 0xcb, 0x4c, 0x4e, 0x15, 0xb2, 0xe3,
	0x62, 0x05, 0xeb, 0x13, 0x92, 0xc0, 0xb0, 0x00, 0xea, 0x18, 0x29, 0x49, 0x2c, 0x32, 0x10, 0x4b,
	0x94, 0x18, 0x9c, 0x38, 0xa2, 0xd8, 0x20, 0xc1, 0x92, 0xc4, 0x06, 0x0e, 0x10, 0x63, 0x40, 0x00,
	0x00, 0x00, 0xff, 0xff, 0x74, 0xca, 0x2e, 0x31, 0x27, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// ProcServiceClient is the client API for ProcService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ProcServiceClient interface {
	// Unary
	Greet(ctx context.Context, in *GreetRequest, opts ...grpc.CallOption) (*GreetResponse, error)
}

type procServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewProcServiceClient(cc grpc.ClientConnInterface) ProcServiceClient {
	return &procServiceClient{cc}
}

func (c *procServiceClient) Greet(ctx context.Context, in *GreetRequest, opts ...grpc.CallOption) (*GreetResponse, error) {
	out := new(GreetResponse)
	err := c.cc.Invoke(ctx, "/first_proc.ProcService/Greet", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProcServiceServer is the server API for ProcService service.
type ProcServiceServer interface {
	// Unary
	Greet(context.Context, *GreetRequest) (*GreetResponse, error)
}

// UnimplementedProcServiceServer can be embedded to have forward compatible implementations.
type UnimplementedProcServiceServer struct {
}

func (*UnimplementedProcServiceServer) Greet(ctx context.Context, req *GreetRequest) (*GreetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Greet not implemented")
}

func RegisterProcServiceServer(s *grpc.Server, srv ProcServiceServer) {
	s.RegisterService(&_ProcService_serviceDesc, srv)
}

func _ProcService_Greet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GreetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProcServiceServer).Greet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/first_proc.ProcService/Greet",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProcServiceServer).Greet(ctx, req.(*GreetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ProcService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "first_proc.ProcService",
	HandlerType: (*ProcServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Greet",
			Handler:    _ProcService_Greet_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "procpb/proc_1.proto",
}
